export interface QuizQuestion {
  id: number;
  readingText?: string;
  text: string;
  type: 'multiple' | 'multiple-complex' | 'true-false-table';
  options?: { id: string; text: string; correct?: boolean }[];
  statements?: { id: string; text: string; correct?: boolean }[];
  correctAnswer?: any;
}

const teks1 = "Pencemaran Laut dan Ancaman Mikroplastik\nLautan di seluruh dunia kini menghadapi ancaman ganda akibat pemanasan global dan pencemaran sampah. Salah satu isu lingkungan yang paling mengkhawatirkan adalah keberadaan sampah plastik. Setiap tahun, jutaan ton sampah plastik bermuara di lautan dan membutuhkan waktu ratusan tahun agar dapat terurai secara alami. Dalam proses penguraian tersebut, partikel plastik pecah menjadi ukuran yang sangat kecil dan dikenal sebagai mikroplastik.\n\nKeberadaan mikroplastik di perairan laut sangat berbahaya bagi keberlangsungan ekosistem perairan. Hewan-hewan laut seperti plankton, ikan kecil, hingga mamalia laut sering kali keliru mengira mikroplastik sebagai sumber makanan. Akibatnya, partikel berbahaya ini masuk ke dalam rantai makanan laut. Ketika manusia mengonsumsi hasil tangkapan laut yang telah terkontaminasi mikroplastik, zat kimia berbahaya tersebut berisiko memicu gangguan kesehatan kronis.\n\nOleh sebab itu, diperlukan mobilisasi seluruh elemen masyarakat, pemerintah, serta sektor industri untuk mengurangi pemakaian plastik sekali pakai. Pemanfaatan material alternatif yang mudah terurai dan perbaikan sistem daur ulang menjadi langkah strategis yang harus segera direalisasikan demi menjaga kelestarian laut bagi generasi mendatang.";

const teks2 = "Kutipan Cerpen: Menatap Padi Menguning\nSepulang sekolah, langkah kaki Ardi terasa sangat berat. Di atas meja belajarnya, buku catatan sains masih terbuka pada halaman materi olimpiade yang harus ia kuasai pekan depan. Namun, suara Ayah dari beranda belakang membuyarkan konsentrasinya.\n\n\"Ardi, mulai besok sore kamu tidak usah ke tempat les sains dulu. Ini sudah masuk musim panen. Ayah butuh kamu untuk membantu menghalau kawanan burung pipit di sawah bagian timur,\" ucap Ayah dengan nada datar tanpa menoleh.\n\nDada Ardi terasa sesak. Ia ingin sekali membantah dan menjelaskan bahwa olimpiade ini adalah kesempatan emas baginya untuk meraih beasiswa. Namun, melihat punggung Ayah yang mulai membungkuk dan peluh yang membasahi kemeja usangnya, kata-kata itu tercekat di tenggorokan. Ardi tahu, panen kali ini adalah satu-satunya tumpuan keluarga untuk melunasi biaya sekolah kakaknya.";

const teks3 = "Bahaya Zat Pewarna Sintetis Rhodamin B\nRhodamin B merupakan zat pewarna sintetis yang pada dasarnya diperuntukkan bagi industri tekstil, kertas, dan cat. Senyawa ini berbentuk kristal kehijauan yang ketika dilarutkan dalam air akan menghasilkan warna merah keunguan cerah serta berpendar jika terkena sinar ultraviolet. Harganya yang relatif murah serta daya warnanya yang kuat membuat zat kimia berbahaya ini kerap disalahgunakan oleh produsen nakal sebagai pewarna makanan, seperti pada sirup, kerupuk, terasi, dan kembang gula.\n\nBadan Pengawas Obat dan Makanan (BPOM) telah melarang keras penggunaan Rhodamin B untuk produk pangan karena memiliki sifat karsinogenik. Paparan Rhodamin B secara berulang dalam jangka panjang dapat memicu penumpukan racun di organ hati dan ginjal, sehingga berpotensi menimbulkan kerusakan jaringan seluler hingga kanker. Masyarakat diimbau untuk lebih teliti dalam memilih pangan olahan dengan menghindari produk yang memiliki warna mencolok tidak wajar.";

const teks4 = "Transformasi Digital dan Pemberdayaan UMKM\nPerkembangan teknologi informasi telah membawa dampak transformatif bagi sektor Usaha Mikro, Kecil, dan Menengah (UMKM). Pemanfaatan platform niaga elektronik (e-commerce) dan sistem pembayaran berbasis kode respons cepat (QRIS) membuka akses pasar yang jauh lebih luas bagi pelaku usaha lokal. Transaksi yang semula terbatas secara geografis kini dapat menjangkau konsumen antardaerah bahkan mancanegara secara instan.\n\nKendati demikian, percepatan digitalisasi ini bukan tanpa hambatan. Tingkat literasi digital para pelaku UMKM masih menjadi tantangan utama yang perlu diatasi. Selain itu, keamanan siber dan perlindungan data pribadi konsumen menuntut perhatian serius agar ekosistem niaga digital tetap aman dan terpercaya. Oleh karena itu, sinergi pelatihan literasi teknologi dari berbagai pihak sangat diperlukan guna mendorong daya saing UMKM di era modern.";

export const indoTryoutData: QuizQuestion[] = [
  { id: 1, readingText: teks1, text: "Makna istilah mobilisasi pada paragraf ketiga teks tersebut adalah...", type: 'multiple', options: [{ id: 'a', text: 'Pengarahan tenaga atau massa untuk bergerak bersama', correct: true }, { id: 'b', text: 'Percepatan proses daur ulang sampah' }, { id: 'c', text: 'Perjalanan dari satu tempat ke tempat lain' }, { id: 'd', text: 'Perencanaan strategi secara matang' }, { id: 'e', text: 'Penilaian kelayakan suatu produk pengganti' }] },
  { id: 2, readingText: teks1, text: "Gagasan utama paragraf pertama pada teks di atas adalah...", type: 'multiple', options: [{ id: 'a', text: 'Manfaat laut bagi kehidupan manusia' }, { id: 'b', text: 'Ancaman pemanasan global dan pencemaran sampah plastik di lautan', correct: true }, { id: 'c', text: 'Waktu yang diperlukan mikroplastik untuk terurai' }, { id: 'd', text: 'Perbedaan antara sampah organik dan plastik' }, { id: 'e', text: 'Proses pemecahan plastik menjadi partikel kecil' }] },
  { id: 3, readingText: teks1, text: "Mengapa mikroplastik berbahaya bagi kesehatan manusia?", type: 'multiple', options: [{ id: 'a', text: 'Menghalangi masuknya sinar matahari ke dasar laut' }, { id: 'b', text: 'Merusak alat tangkap ikan tradisional milik nelayan' }, { id: 'c', text: 'Masuk ke dalam rantai makanan laut dan terkonsumsi oleh manusia', correct: true }, { id: 'd', text: 'Mengurangi kadar oksigen di atmosfer secara drastis' }, { id: 'e', text: 'Memicu kenaikan suhu permukaan air laut secara mendadak' }] },
  { id: 4, readingText: teks1, text: "Simpulan yang tepat dari teks bacaan tersebut adalah...", type: 'multiple', options: [{ id: 'a', text: 'Sampah plastik hanya dapat diatasi jika masyarakat berhenti mengonsumsi ikan.' }, { id: 'b', text: 'Mikroplastik tidak berbahaya selama ikan diolah dengan temperatur tinggi.' }, { id: 'c', text: 'Lautan akan bersih dengan sendirinya tanpa bantuan kebijakan pemerintah.' }, { id: 'd', text: 'Upaya bersama lintas sektor dalam mengurangi plastik sekali pakai sangat krusial untuk melindungi ekosistem laut.', correct: true }, { id: 'e', text: 'Pemanasan global merupakan penyebab utama terbentuknya mikroplastik.' }] },
  { id: 5, readingText: teks2, text: "Konflik batin yang dialami oleh tokoh Ardi dalam kutipan cerpen di atas adalah...", type: 'multiple', options: [{ id: 'a', text: 'Keinginan untuk pindah sekolah ke luar kota' }, { id: 'b', text: 'Perselisihan sengit dengan sang kakak mengenai biaya sekolah' }, { id: 'c', text: 'Dilema antara mengejar impian olimpiade atau membantu beban ekonomi ayahnya di sawah', correct: true }, { id: 'd', text: 'Rasa malas belajar menjelang ujian akhir sekolah' }, { id: 'e', text: 'Kekecewaan karena gagal dalam seleksi olimpiade tingkat kabupaten' }] },
  { id: 6, readingText: teks2, text: "Penyebab terjadinya konflik pada kutipan cerita tersebut adalah...", type: 'multiple', options: [{ id: 'a', text: 'Kakak Ardi menolak membantu pekerjaan ayahnya' }, { id: 'b', text: 'Ayah meminta Ardi berhenti les demi membantu panen di sawah', correct: true }, { id: 'c', text: 'Ardi tidak memahami materi olimpiade sains yang diajarkan' }, { id: 'd', text: 'Burung pipit menghancurkan seluruh hasil panen di sawah timur' }, { id: 'e', text: 'Pihak sekolah membatalkan pendaftaran olimpiade Ardi' }] },
  { id: 7, readingText: teks2, text: "Watak tokoh Ardi yang tergambar dalam kutipan tersebut adalah...", type: 'multiple', options: [{ id: 'a', text: 'Pemarah dan pendendam' }, { id: 'b', text: 'Keras kepala dan egois' }, { id: 'c', text: 'Berbakti dan penuh pengertian', correct: true }, { id: 'd', text: 'Putus asa dan pasif' }, { id: 'e', text: 'Ceroboh dan pembangkang' }] },
  { id: 8, readingText: teks2, text: "Nilai moral yang dapat dipetik dari kutipan cerpen di atas adalah...", type: 'multiple', options: [{ id: 'a', text: 'Menuntut hak tanpa memedulikan kondisi keluarga' }, { id: 'b', text: 'Menghindari pekerjaan fisik agar dapat berprestasi' }, { id: 'c', text: 'Memahami pengorbanan orang tua dan bersikap bijak menghadapi keadaan', correct: true }, { id: 'd', text: 'Mengabaikan pendidikan demi kepentingan jangka pendek' }, { id: 'e', text: 'Menyelesaikan masalah keluarga dengan cara berdebat terbuka' }] },
  { id: 9, readingText: teks3, text: "Tujuan penulisan teks tersebut adalah untuk...", type: 'multiple', options: [{ id: 'a', text: 'Memberikan tutorial cara pembuatan pewarna tekstil secara mandiri' }, { id: 'b', text: 'Menginformasikan bahaya penyalahgunaan Rhodamin B dalam makanan bagi kesehatan tubuh', correct: true }, { id: 'c', text: 'Mempromosikan penggunaan pewarna sintetis berharga murah' }, { id: 'd', text: 'Membandingkan daya tahan warna Rhodamin B dengan pewarna alami' }, { id: 'e', text: 'Menganalisis omzet produsen kerupuk dan sirup di pasaran' }] },
  { id: 10, readingText: teks3, text: "Ciri fisik Rhodamin B berdasarkan teks bacaan tersebut adalah...", type: 'multiple', options: [{ id: 'a', text: 'Serbuk putih tanpa aroma dan larut dalam minyak' }, { id: 'b', text: 'Cairan kental berwarna kuning kecokelatan' }, { id: 'c', text: 'Serbuk kristal kehijauan yang larut menghasilkan warna merah keunguan cerah', correct: true }, { id: 'd', text: 'Butiran kasar berwarna biru dongker yang tidak larut dalam air' }, { id: 'e', text: 'Kristal transparan yang berubah warna saat dipanaskan' }] },
  { id: 11, readingText: teks3, text: "Kalimat yang mengandung hubungan sebab-akibat (kausalitas) pada teks di atas adalah...", type: 'multiple', options: [{ id: 'a', text: '\"Rhodamin B merupakan zat pewarna sintetis yang pada dasarnya diperuntukkan bagi industri tekstil...\"' }, { id: 'b', text: '\"Harganya yang relatif murah serta daya warnanya yang kuat membuat zat kimia berbahaya ini kerap disalahgunakan...\"', correct: true }, { id: 'c', text: '\"Senyawa ini berbentuk kristal kehijauan yang ketika dilarutkan dalam air akan menghasilkan warna merah...\"' }, { id: 'd', text: '\"BPOM telah melarang keras penggunaan Rhodamin B untuk produk pangan...\"' }, { id: 'e', text: '\"Masyarakat diimbau untuk lebih teliti dalam memilih pangan olahan...\"' }] },
  { id: 12, readingText: teks3, text: "Langkah pencegahan yang disarankan penulis kepada masyarakat adalah...", type: 'multiple', options: [{ id: 'a', text: 'Memeriksa kandungan kimia makanan menggunakan mikroskop pribadi' }, { id: 'b', text: 'Menghentikan konsumsi semua jenis makanan yang memiliki rasa manis' }, { id: 'c', text: 'Menghindari produk pangan yang memiliki warna mencolok tidak wajar', correct: true }, { id: 'd', text: 'Membeli produk pangan hanya yang diproduksi oleh industri tekstil' }, { id: 'e', text: 'Melarutkan semua makanan ke dalam air sebelum dikonsumsi' }] },
  { id: 13, readingText: teks4, text: "Ide pokok paragraf pertama teks tersebut adalah...", type: 'multiple', options: [{ id: 'a', text: 'Prosedur pembuatan kode respons cepat bagi pelaku usaha mikro' }, { id: 'b', text: 'Keunggulan transaksi tunai dibandingkan pembayaran digital' }, { id: 'c', text: 'Dampak positif kemajuan teknologi terhadap perluasan pasar UMKM', correct: true }, { id: 'd', text: 'Kegagalan produk UMKM menembus pasar internasional' }, { id: 'e', text: 'Biaya langganan platform niaga elektronik di Indonesia' }] },
  { id: 14, readingText: teks4, text: "Kata penghubung (konjungsi) antarkalimat yang menyatakan pertentangan pada paragraf kedua adalah...", type: 'multiple', options: [{ id: 'a', text: 'Selain itu' }, { id: 'b', text: 'Oleh karena itu' }, { id: 'c', text: 'Kendati demikian', correct: true }, { id: 'd', text: 'Bahkan' }, { id: 'e', text: 'Agar' }] },
  { id: 15, readingText: teks4, text: "Tantangan utama yang dihadapi UMKM dalam proses digitalisasi menurut teks adalah...", type: 'multiple', options: [{ id: 'a', text: 'Tingginya harga bahan baku lokal' }, { id: 'b', text: 'Ketiadaan perangkat telepon pintar di pasaran' }, { id: 'c', text: 'Rendahnya minat konsumen terhadap belanja daring' }, { id: 'd', text: 'Rendahnya tingkat literasi digital dan risiko keamanan siber', correct: true }, { id: 'e', text: 'Larangan transaksi antarpulau oleh otoritas berwenang' }] },
  { id: 16, readingText: teks4, text: "Pola pengembangan paragraf kedua pada teks tersebut adalah...", type: 'multiple', options: [{ id: 'a', text: 'Kronologis (urutan waktu)' }, { id: 'b', text: 'Definisi umum' }, { id: 'c', text: 'Masalah dan solusi', correct: true }, { id: 'd', text: 'Analogi' }, { id: 'e', text: 'Narasi fiktif' }] },
  { id: 17, text: "Penulisan kata serapan yang baku untuk memperbaiki kata 'proyeck' dan 'revitallisasi' dalam kalimat \"Pemerintah merencanakan proyeck revitallisasi infrastruktur perkotaan demi kenyamanan publik.\" adalah...", type: 'multiple', options: [{ id: 'a', text: 'Proyek, revitalisasi', correct: true }, { id: 'b', text: 'Projek, revitallisasi' }, { id: 'c', text: 'Proyek, revitallisasi' }, { id: 'd', text: 'Projek, revitalisasi' }, { id: 'e', text: 'Proyeck, revitalisir' }] },
  { id: 18, text: "Penggunaan tanda baca titik dua (:) yang tepat terdapat pada kalimat: \"Ayah membeli buah-buahan di pasar: apel, jeruk, dan mangga.\" (Kalimat 2). Tentukan Benar atau Salah!", type: 'true-false-table', statements: [{ id: 's1', text: 'Benar', correct: true }, { id: 's2', text: 'Salah', correct: false }] },
  { id: 19, text: "Konjungsi subordinatif yang tepat untuk melengkapi kalimat \"Krisis energi global tidak akan teratasi [...] masyarakat dunia belum beralih ke sumber energi terbarukan.\" adalah...", type: 'multiple', options: [{ id: 'a', text: 'sehingga' }, { id: 'b', text: 'jika', correct: true }, { id: 'c', text: 'meskipun' }, { id: 'd', text: 'bahwa' }, { id: 'e', text: 'lalu' }] },
  { id: 20, text: "Kalimat efektif yang benar adalah \"Mahasiswa yang terlambat masuk ke dalam ruangan tidak diperkenankan mengikuti ujian.\"", type: 'true-false-table', statements: [{ id: 's1', text: 'Tepat', correct: true }, { id: 's2', text: 'Tidak Tepat', correct: false }] }
];
