/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import React, { useState, useRef, useEffect } from 'react';
import { Bot, Send, Sparkles, BookOpen, Key, BrainCircuit, Play, Check, HelpCircle, X, Layers, User, Maximize2, Minimize2 } from 'lucide-react';
import { Question } from '../types';
import MathMarkdown from './MathMarkdown';
import { getAiKnowledgeBase } from '../lib/firestoreSimulator';

const ALL_SUBJECTS = [
  { name: 'Matematika Umum', icon: '📐', defaultTopic: 'Persamaan & Fungsi Kuadrat' },
  { name: 'Matematika Lanjut', icon: '📊', defaultTopic: 'Matriks & Polinomial' },
  { name: 'Fisika', icon: '⚡', defaultTopic: 'Dinamika Rotasi & Kinematika' },
  { name: 'Kimia', icon: '🧪', defaultTopic: 'Stoikiometri & Laju Reaksi' },
  { name: 'Biologi', icon: '🧬', defaultTopic: 'Sintesis Protein & Genetika' },
  { name: 'Ekonomi', icon: '📈', defaultTopic: 'Akuntansi & Pasar Modal' },
  { name: 'Geografi', icon: '🌍', defaultTopic: 'Penginderaan Jauh & Atmosfer' },
  { name: 'Sejarah', icon: '📜', defaultTopic: 'Peristiwa Proklamasi & Orba' },
  { name: 'Sosiologi', icon: '👥', defaultTopic: 'Interaksi & Konflik Sosial' },
  { name: 'Bahasa Indonesia', icon: '📚', defaultTopic: 'Teks Argumentasi & PUEBI' },
  { name: 'Bahasa Inggris', icon: '🇬🇧', defaultTopic: 'Reading Comprehension' },
  { name: 'Potensi Skolastik', icon: '🧠', defaultTopic: 'Penalaran Logis & Kuantitatif' },
];

interface Message {
  role: 'user' | 'model';
  text: string;
}

interface AiTutorSandboxProps {
  userProfile: any;
}

export default function AiTutorSandbox({ userProfile }: AiTutorSandboxProps) {
  const [messages, setMessages] = useState<Message[]>([
    {
      role: 'model',
      text: `Halo ${userProfile?.displayName || 'Siswa'}! 👋 Saya adalah AI Tutor cerdas TKA SMA Indonesia.

Saya mendukung format penulisan **LaTeX** untuk menyajikan rumus Matematika (misalnya $x = \\frac{-b \\pm \\sqrt{b^2 - 4ac}}{2a}$), persamaan Fisika ($F = m \\cdot a$), reaksi Kimia, dan konsep TKA lainnya secara super rapi dan presisi.

Silakan tanyakan materi apa pun, atau pilih salah satu **Tugas Pintar** di bawah!`
    }
  ]);
  const [input, setInput] = useState('');
  const [loading, setLoading] = useState(false);
  const [loadingQuiz, setLoadingQuiz] = useState(false);
  
  // Custom quiz generated by AI
  const [aiQuiz, setAiQuiz] = useState<Question[]>([]);
  const [quizAnswers, setQuizAnswers] = useState<{ [qId: string]: number }>({});
  const [quizSubmitted, setQuizSubmitted] = useState(false);

  // Fullscreen mode: 'none' | 'all' | 'chat' | 'quiz'
  const [fullscreenMode, setFullscreenMode] = useState<'none' | 'all' | 'chat' | 'quiz'>('none');

  useEffect(() => {
    const handleKeyDown = (e: KeyboardEvent) => {
      if (e.key === 'Escape') {
        setFullscreenMode('none');
      }
    };
    window.addEventListener('keydown', handleKeyDown);
    return () => window.removeEventListener('keydown', handleKeyDown);
  }, []);

  // Subject and Topic selector state
  const [selectedSubject, setSelectedSubject] = useState<string>('Matematika Umum');
  const [customTopic, setCustomTopic] = useState<string>('Persamaan & Fungsi Kuadrat');

  const handleSubjectChange = (subjectName: string) => {
    setSelectedSubject(subjectName);
    const found = ALL_SUBJECTS.find(s => s.name === subjectName);
    if (found) {
      setCustomTopic(found.defaultTopic);
    }
  };

  const chatEndRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    chatEndRef.current?.scrollIntoView({ behavior: 'smooth' });
  }, [messages]);

  const handleSend = async (textToSend: string) => {
    if (!textToSend.trim() || loading) return;

    const userMessage: Message = { role: 'user', text: textToSend };
    setMessages((prev) => [...prev, userMessage]);
    setInput('');
    setLoading(true);

    try {
      // Proxying request to express server-side Gemini route
      const response = await fetch('/api/ai/chat', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          message: textToSend,
          aiKnowledgeBase: getAiKnowledgeBase(),
          context: {
            userProfile: {
              displayName: userProfile.displayName,
              targetPTN: userProfile.targetPTN,
              targetProdi: userProfile.targetProdi,
              isPremium: userProfile.isPremium
            }
          },
          history: messages.slice(-10) // Send latest conversation context
        })
      });

      if (!response.ok) {
        throw new Error('Gagal menghubungi AI Server');
      }

      const data = await response.json();
      setMessages((prev) => [...prev, { role: 'model', text: data.text || 'Maaf, saya tidak mendapatkan respons dari server.' }]);
    } catch (error: any) {
      setMessages((prev) => [
        ...prev,
        { role: 'model', text: '❌ Gagal menghubungi AI Server. Pastikan Server Anda aktif atau coba kembali.' }
      ]);
    } finally {
      setLoading(false);
    }
  };

  const handleSmartAction = (actionType: 'summary' | 'trick' | 'quiz') => {
    if (actionType === 'summary') {
      const prompt = 'Tolong buatkan ringkasan materi singkat dan rumus inti mengenai "Turunan Fungsi Aljabar" kelas XII SMA.';
      handleSend(prompt);
    } else if (actionType === 'trick') {
      const prompt = 'Berikan saya "Trik Cepat Kilat" pengerjaan soal Dinamika Rotasi Fisika model UTBK TKA.';
      handleSend(prompt);
    } else if (actionType === 'quiz') {
      handleGenerateQuiz('Matematika Umum', 'Persamaan Kuadrat');
    }
  };

  const handleGenerateQuiz = async (subject: string, topic: string) => {
    setLoadingQuiz(true);
    setAiQuiz([]);
    setQuizAnswers({});
    setQuizSubmitted(false);

    // Let student know AI is thinking
    setMessages((prev) => [
      ...prev,
      { role: 'user', text: `Buatkan saya kuis instan 3 soal materi ${subject} - ${topic}` },
      { role: 'model', text: `Sedang menyiapkan soal kuis eksklusif menggunakan Gemini AI... Harap tunggu beberapa detik. ⚡` }
    ]);

    try {
      const response = await fetch('/api/ai/generate-quiz', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ subject, topic })
      });

      if (!response.ok) throw new Error('Gagal generate kuis');
      const data = await response.json();
      
      if (Array.isArray(data) && data.length > 0) {
        // Form IDs
        const formatted: Question[] = data.map((q: any, idx: number) => ({
          id: `ai_q_${idx}_${Date.now()}`,
          text: q.text,
          options: q.options || ['A', 'B', 'C', 'D', 'E'],
          correctAnswerIndex: q.correctAnswerIndex !== undefined ? q.correctAnswerIndex : 0,
          correctAnswer: q.correctAnswer || 'A',
          explanation: q.explanation || 'Pembahasan selesai.',
          difficulty: q.difficulty || 'Sedang',
          bab: q.topic || topic,
          year: '2026',
          subject
        }));

        setAiQuiz(formatted);
        setMessages((prev) => [
          ...prev,
          { role: 'model', text: `✨ Sukses! 3 Soal kuis interaktif mengenai ${subject} telah siap di kerjakan di panel samping!` }
        ]);
      } else {
        throw new Error('Format kuis tidak valid');
      }
    } catch (e) {
      setMessages((prev) => [
        ...prev,
        { role: 'model', text: `Maaf, terjadi kendala saat generate kuis otomatis. Silakan coba kembali.` }
      ]);
    } finally {
      setLoadingQuiz(false);
    }
  };

  const handleQuizSelect = (qId: string, optIndex: number) => {
    if (quizSubmitted) return;
    setQuizAnswers((prev) => ({ ...prev, [qId]: optIndex }));
  };

  const handleSubmitQuiz = () => {
    setQuizSubmitted(true);
  };

  return (
    <div
      className={`bg-white border border-slate-100 shadow-sm flex flex-col transition-all duration-300 ${
        fullscreenMode === 'all'
          ? 'fixed inset-0 z-50 h-screen w-screen rounded-none shadow-2xl'
          : 'rounded-2xl h-[80vh]'
      }`}
      id="ai-tutor-sandbox"
    >
      {/* Header */}
      <div className="bg-slate-900 text-white p-4 sm:p-5 flex items-center justify-between border-b border-slate-800 shrink-0">
        <div className="flex items-center gap-3">
          <div className="bg-blue-600 p-2 rounded-xl text-white shrink-0">
            <Bot className="w-5 h-5" />
          </div>
          <div>
            <h3 className="font-bold text-sm sm:text-base flex items-center gap-1.5">
              AI Tutor Pintar <Sparkles className="w-4 h-4 text-amber-400 animate-pulse" />
            </h3>
            <p className="text-xs text-slate-400">Gemini 3.5 Flash Model - Active</p>
          </div>
        </div>
        <div className="flex items-center gap-2">
          <div className="hidden md:block text-xs bg-slate-800 text-slate-300 px-3 py-1 rounded-full border border-slate-700">
            Quota: Tak Terbatas
          </div>
          <button
            onClick={() => setFullscreenMode(fullscreenMode === 'all' ? 'none' : 'all')}
            className="flex items-center gap-1.5 text-xs font-bold bg-blue-600 hover:bg-blue-500 text-white px-3 py-1.5 rounded-xl transition-all shadow-sm cursor-pointer"
            title="Full Screen Seluruh Sandbox"
          >
            {fullscreenMode === 'all' ? <Minimize2 className="w-3.5 h-3.5" /> : <Maximize2 className="w-3.5 h-3.5" />}
            <span className="hidden sm:inline">{fullscreenMode === 'all' ? 'Keluar Full Screen' : 'Full Screen All'}</span>
          </button>
        </div>
      </div>

      <div className="flex-1 grid grid-cols-1 lg:grid-cols-12 overflow-hidden">
        
        {/* Chat Conversation Area */}
        <div
          className={`flex flex-col h-full overflow-hidden bg-slate-50/50 ${
            fullscreenMode === 'quiz' ? 'hidden' : ''
          } ${
            fullscreenMode === 'chat'
              ? 'fixed inset-0 z-50 bg-white'
              : 'lg:col-span-7 border-r border-slate-100'
          }`}
        >
          {/* Chat Sub-Header with Full Screen Chat toggle */}
          <div className="p-3 border-b border-slate-100 bg-white flex justify-between items-center shrink-0 shadow-2xs">
            <div className="flex items-center gap-2">
              <Bot className="w-4 h-4 text-blue-600" />
              <span className="text-xs font-extrabold text-slate-700 uppercase tracking-widest">
                {fullscreenMode === 'chat' ? 'AI Tutor Pintar — Full Screen Chat' : 'Chat AI Tutor'}
              </span>
            </div>
            <button
              onClick={() => setFullscreenMode(fullscreenMode === 'chat' ? 'none' : 'chat')}
              className="flex items-center gap-1.5 text-xs font-bold text-slate-600 hover:text-blue-600 px-2.5 py-1 rounded-lg bg-slate-50 hover:bg-blue-50 border border-slate-200 hover:border-blue-200 transition-all cursor-pointer"
              title="Full Screen Chat"
            >
              {fullscreenMode === 'chat' ? <Minimize2 className="w-3.5 h-3.5 text-blue-600" /> : <Maximize2 className="w-3.5 h-3.5 text-slate-500" />}
              <span>{fullscreenMode === 'chat' ? 'Kecilkan Chat' : 'Full Screen Chat'}</span>
            </button>
          </div>
          
          {/* Messages scroll area */}
          <div className={`flex-1 p-5 overflow-y-auto space-y-4 ${fullscreenMode === 'chat' ? 'max-w-4xl mx-auto w-full' : ''}`}>
            {messages.map((msg, idx) => (
              <div
                key={idx}
                className={`flex gap-3 max-w-[85%] ${
                  msg.role === 'user' ? 'ml-auto flex-row-reverse' : 'mr-auto'
                }`}
              >
                <div
                  className={`w-8 h-8 rounded-full flex items-center justify-center shrink-0 ${
                    msg.role === 'user' ? 'bg-blue-100 text-blue-700' : 'bg-slate-900 text-white'
                  }`}
                >
                  {msg.role === 'user' ? <User className="w-4 h-4" /> : <Bot className="w-4 h-4" />}
                </div>
                <div
                  className={`p-4 sm:p-5 rounded-2xl text-xs sm:text-sm shadow-sm leading-[1.85] tracking-wide ${
                    msg.role === 'user'
                      ? 'bg-blue-600 text-white rounded-tr-none whitespace-pre-wrap'
                      : 'bg-white border border-slate-100 text-slate-800 rounded-tl-none'
                  }`}
                >
                  {msg.role === 'user' ? (
                    msg.text
                  ) : (
                    <MathMarkdown content={msg.text} />
                  )}
                </div>
              </div>
            ))}
            {loading && (
              <div className="flex gap-3 max-w-[80%] mr-auto items-center">
                <div className="w-8 h-8 rounded-full bg-slate-900 text-white flex items-center justify-center">
                  <Bot className="w-4 h-4 animate-bounce" />
                </div>
                <div className="bg-white border border-slate-100 p-4 rounded-2xl rounded-tl-none flex items-center gap-2">
                  <span className="flex h-2 w-2 rounded-full bg-blue-600 animate-ping"></span>
                  <span className="text-xs text-slate-500 font-semibold">Tutor sedang mengetik pembahasan...</span>
                </div>
              </div>
            )}
            <div ref={chatEndRef} />
          </div>

          {/* Quick task tools */}
          <div className={`p-3 border-t border-slate-100 bg-white grid grid-cols-3 gap-2 shrink-0 ${fullscreenMode === 'chat' ? 'max-w-4xl mx-auto w-full' : ''}`}>
            <button
              onClick={() => handleSmartAction('summary')}
              className="py-2.5 px-2 rounded-xl bg-blue-50/50 hover:bg-blue-50 border border-blue-100 text-[10px] sm:text-xs font-bold text-blue-700 flex flex-col sm:flex-row items-center justify-center gap-1.5 transition-all text-center cursor-pointer"
            >
              <BookOpen className="w-3.5 h-3.5 shrink-0" />
              <span>Ringkas Turunan</span>
            </button>
            <button
              onClick={() => handleSmartAction('trick')}
              className="py-2.5 px-2 rounded-xl bg-orange-50/50 hover:bg-orange-50 border border-orange-100 text-[10px] sm:text-xs font-bold text-orange-700 flex flex-col sm:flex-row items-center justify-center gap-1.5 transition-all text-center cursor-pointer"
            >
              <BrainCircuit className="w-3.5 h-3.5 shrink-0" />
              <span>Trik Rotasi Fisika</span>
            </button>
            <button
              onClick={() => handleSmartAction('quiz')}
              className="py-2.5 px-2 rounded-xl bg-emerald-50/50 hover:bg-emerald-50 border border-emerald-100 text-[10px] sm:text-xs font-bold text-emerald-700 flex flex-col sm:flex-row items-center justify-center gap-1.5 transition-all text-center cursor-pointer"
            >
              <Sparkles className="w-3.5 h-3.5 shrink-0 animate-pulse" />
              <span>Kuis Instan AI</span>
            </button>
          </div>

          {/* Chat Form Input */}
          <form
            onSubmit={(e) => {
              e.preventDefault();
              handleSend(input);
            }}
            className={`p-4 bg-white border-t border-slate-100 flex gap-3 shrink-0 ${fullscreenMode === 'chat' ? 'max-w-4xl mx-auto w-full' : ''}`}
          >
            <input
              type="text"
              placeholder="Tanyakan rumus, pembahasan, atau kuis materi di sini..."
              value={input}
              onChange={(e) => setInput(e.target.value)}
              disabled={loading}
              className="flex-1 px-4 py-3 border border-slate-200 rounded-xl text-xs sm:text-sm focus:outline-none focus:border-blue-500 disabled:opacity-50"
            />
            <button
              type="submit"
              disabled={loading || !input.trim()}
              className="px-5 py-3 rounded-xl bg-blue-600 hover:bg-blue-700 disabled:bg-slate-200 text-white font-semibold transition-all shadow-md shadow-blue-100 flex items-center justify-center cursor-pointer shrink-0"
            >
              <Send className="w-4 h-4" />
            </button>
          </form>

        </div>

        {/* AI Quiz Playground (Right Side) */}
        <div
          className={`flex flex-col h-full overflow-hidden bg-white ${
            fullscreenMode === 'chat' ? 'hidden' : ''
          } ${
            fullscreenMode === 'quiz'
              ? 'fixed inset-0 z-50 bg-white'
              : 'lg:col-span-5'
          }`}
        >
          <div className="p-3.5 border-b border-slate-100 bg-slate-50 flex justify-between items-center shrink-0">
            <h4 className="text-xs font-extrabold text-slate-700 uppercase tracking-widest flex items-center gap-1.5">
              <BrainCircuit className="w-4 h-4 text-emerald-600" />
              {fullscreenMode === 'quiz' ? 'AI Kuis Playground — Full Screen' : 'AI Kuis Playground'}
            </h4>
            <div className="flex items-center gap-2">
              {loadingQuiz && <span className="text-[10px] text-blue-600 font-bold animate-pulse">Membuat soal...</span>}
              <button
                onClick={() => setFullscreenMode(fullscreenMode === 'quiz' ? 'none' : 'quiz')}
                className="flex items-center gap-1.5 text-xs font-bold text-slate-600 hover:text-emerald-700 px-2.5 py-1 rounded-lg bg-white hover:bg-emerald-50 border border-slate-200 hover:border-emerald-200 transition-all cursor-pointer shadow-2xs"
                title="Full Screen Kuis"
              >
                {fullscreenMode === 'quiz' ? <Minimize2 className="w-3.5 h-3.5 text-emerald-600" /> : <Maximize2 className="w-3.5 h-3.5 text-slate-500" />}
                <span>{fullscreenMode === 'quiz' ? 'Kecilkan Kuis' : 'Full Screen Kuis'}</span>
              </button>
            </div>
          </div>

          <div className={`flex-1 p-4 overflow-y-auto space-y-5 ${fullscreenMode === 'quiz' ? 'max-w-5xl mx-auto w-full' : ''}`}>
            {/* Subject Generator Form */}
            <div className="bg-slate-50/80 border border-slate-200/60 p-3.5 rounded-2xl space-y-3 shadow-xs">
              <div className="flex items-center justify-between">
                <span className="text-[11px] font-extrabold text-slate-800 uppercase tracking-wider flex items-center gap-1">
                  <Layers className="w-3.5 h-3.5 text-blue-600" /> Pilih Mata Pelajaran Kuis
                </span>
                <span className="text-[9px] bg-emerald-100 text-emerald-700 font-bold px-2 py-0.5 rounded-full">
                  12 Mapel TKA
                </span>
              </div>

              <div className="space-y-2">
                <div>
                  <label className="text-[10px] font-bold text-slate-500 uppercase tracking-wide block mb-1">
                    Mata Pelajaran:
                  </label>
                  <select
                    value={selectedSubject}
                    onChange={(e) => handleSubjectChange(e.target.value)}
                    className="w-full px-3 py-2 bg-white border border-slate-200 rounded-xl text-xs font-bold text-slate-800 focus:outline-none focus:ring-1 focus:ring-blue-500"
                  >
                    {ALL_SUBJECTS.map((s) => (
                      <option key={s.name} value={s.name}>
                        {s.icon} {s.name}
                      </option>
                    ))}
                  </select>
                </div>

                <div>
                  <label className="text-[10px] font-bold text-slate-500 uppercase tracking-wide block mb-1">
                    Bab / Topik Soal:
                  </label>
                  <input
                    type="text"
                    value={customTopic}
                    onChange={(e) => setCustomTopic(e.target.value)}
                    placeholder="Contoh: Persamaan Kuadrat, Dinamika Rotasi..."
                    className="w-full px-3 py-1.5 bg-white border border-slate-200 rounded-xl text-xs text-slate-800 focus:outline-none focus:ring-1 focus:ring-blue-500"
                  />
                </div>

                <button
                  onClick={() => handleGenerateQuiz(selectedSubject, customTopic)}
                  disabled={loadingQuiz}
                  className="w-full py-2.5 bg-emerald-600 hover:bg-emerald-700 disabled:opacity-50 text-white font-bold rounded-xl text-xs flex items-center justify-center gap-1.5 transition-all shadow-md shadow-emerald-100 cursor-pointer"
                >
                  <Sparkles className="w-3.5 h-3.5 animate-pulse" />
                  <span>Generate Kuis {selectedSubject} (15 Soal)</span>
                </button>
              </div>
            </div>

            {aiQuiz.length === 0 ? (
              <div className="space-y-3">
                <div className="text-center pt-2 pb-1">
                  <h5 className="font-extrabold text-slate-800 text-xs uppercase tracking-wider">
                    ⚡ Akses Cepat Semua Mata Pelajaran
                  </h5>
                  <p className="text-[11px] text-slate-400 mt-0.5">
                    Klik salah satu mata pelajaran di bawah untuk langsung memicu kuis AI instan (15 Soal):
                  </p>
                </div>

                {/* Grid of ALL 12 Subjects */}
                <div className="grid grid-cols-2 gap-2">
                  {ALL_SUBJECTS.map((s) => (
                    <button
                      key={s.name}
                      onClick={() => {
                        handleSubjectChange(s.name);
                        handleGenerateQuiz(s.name, s.defaultTopic);
                      }}
                      className="p-2.5 bg-white hover:bg-emerald-50/50 border border-slate-200/80 hover:border-emerald-300 rounded-xl text-left transition-all flex items-center gap-2 group cursor-pointer shadow-2xs"
                    >
                      <span className="text-base p-1.5 bg-slate-50 group-hover:bg-white rounded-lg border border-slate-100 shrink-0">
                        {s.icon}
                      </span>
                      <div className="overflow-hidden">
                        <div className="font-bold text-[11px] text-slate-800 group-hover:text-emerald-700 truncate">
                          {s.name}
                        </div>
                        <div className="text-[9px] text-slate-400 truncate">
                          {s.defaultTopic}
                        </div>
                      </div>
                    </button>
                  ))}
                </div>
              </div>
            ) : (
              <div className="space-y-5 border-t border-slate-100 pt-3">
                <div className="bg-emerald-50 border border-emerald-100 p-3 rounded-xl text-xs flex justify-between items-center">
                  <div>
                    <span className="font-extrabold text-emerald-900 block">{selectedSubject}</span>
                    <span className="text-[10px] text-emerald-700">Bab: {aiQuiz[0].bab}</span>
                  </div>
                  <div className="flex items-center gap-2">
                    <span className="font-bold bg-emerald-200/60 text-emerald-800 px-2 py-0.5 rounded text-[10px]">{aiQuiz.length} Soal Ganda</span>
                    <button
                      onClick={() => {
                        setAiQuiz([]);
                        setQuizAnswers({});
                        setQuizSubmitted(false);
                      }}
                      className="p-1 rounded-full bg-emerald-100 hover:bg-emerald-200 text-emerald-800 transition-colors cursor-pointer"
                      title="Ganti Kuis / Reset"
                    >
                      <X className="w-3.5 h-3.5" />
                    </button>
                  </div>
                </div>

                {aiQuiz.map((q, qIdx) => {
                  const isCorrect = quizAnswers[q.id] === q.correctAnswerIndex;
                  return (
                    <div key={q.id} className="border border-slate-200/80 p-4 rounded-xl space-y-3 shadow-xs bg-slate-50/40">
                      <div className="flex items-start gap-2">
                        <span className="bg-slate-900 text-white text-[10px] font-bold px-2 py-0.5 rounded shrink-0 mt-0.5">
                          Soal {qIdx + 1}
                        </span>
                        <div className="flex-1">
                          <MathMarkdown content={q.text} className="font-bold text-slate-800" />
                        </div>
                      </div>

                      <div className="space-y-1.5 pl-2 sm:pl-4">
                        {q.options.map((opt, oIdx) => {
                          const isSelected = quizAnswers[q.id] === oIdx;
                          let btnClass = "border-slate-200 bg-white text-slate-700 hover:bg-slate-50";

                          if (isSelected) {
                            btnClass = "border-blue-500 bg-blue-50 text-blue-800 font-semibold";
                          }

                          if (quizSubmitted) {
                            if (oIdx === q.correctAnswerIndex) {
                              btnClass = "border-emerald-500 bg-emerald-50 text-emerald-800 font-semibold";
                            } else if (isSelected && !isCorrect) {
                              btnClass = "border-red-500 bg-red-50 text-red-800";
                            } else {
                              btnClass = "border-slate-100 bg-slate-50 opacity-60";
                            }
                          }

                          return (
                            <button
                              key={oIdx}
                              onClick={() => handleQuizSelect(q.id, oIdx)}
                              className={`w-full text-left p-2.5 border rounded-lg text-xs flex items-center gap-2 transition-all cursor-pointer ${btnClass}`}
                            >
                              <span className="w-5 h-5 shrink-0 rounded-full bg-slate-100 text-slate-600 font-extrabold flex items-center justify-center text-[10px]">
                                {String.fromCharCode(65 + oIdx)}
                              </span>
                              <MathMarkdown content={opt} className="flex-1 overflow-x-auto text-left" />
                              {quizSubmitted && oIdx === q.correctAnswerIndex && (
                                <Check className="w-3.5 h-3.5 text-emerald-600 ml-auto shrink-0" />
                              )}
                            </button>
                          );
                        })}
                      </div>

                      {quizSubmitted && (
                        <div className="bg-white border border-slate-200/80 p-3 rounded-lg text-xs leading-relaxed space-y-1">
                          <span className="font-bold text-slate-800 block">Kunci & Pembahasan:</span>
                          <MathMarkdown content={q.explanation} className="text-slate-600" />
                        </div>
                      )}
                    </div>
                  );
                })}

                {!quizSubmitted ? (
                  <button
                    onClick={handleSubmitQuiz}
                    disabled={Object.keys(quizAnswers).length < aiQuiz.length}
                    className="w-full py-3 bg-emerald-600 hover:bg-emerald-700 disabled:bg-slate-200 text-white font-bold rounded-xl text-xs transition-colors shadow-md shadow-emerald-50 cursor-pointer"
                  >
                    Kumpulkan Jawaban Kuis
                  </button>
                ) : (
                  <div className="space-y-3">
                    <div className="text-center p-3 bg-blue-50 text-blue-800 font-bold rounded-xl text-xs">
                      🎉 Kuis {selectedSubject} Selesai! XP kamu telah bertambah.
                    </div>
                    <button
                      onClick={() => {
                        setAiQuiz([]);
                        setQuizAnswers({});
                        setQuizSubmitted(false);
                      }}
                      className="w-full py-2.5 bg-slate-100 hover:bg-slate-200 text-slate-700 font-bold rounded-xl text-xs transition-colors cursor-pointer"
                    >
                      Pilih Mata Pelajaran Lain
                    </button>
                  </div>
                )}
              </div>
            )}
          </div>
        </div>

      </div>
    </div>
  );
}

function UserIcon() {
  return (
    <svg className="w-4 h-4" fill="none" viewBox="0 0 24 24" stroke="currentColor">
      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M16 7a4 4 0 11-8 0 4 4 0 018 0zM12 14a7 7 0 00-7 7h14a7 7 0 00-7-7z" />
    </svg>
  );
}
